In [45]:
import pandas as pd
import numpy as np

In [46]:
data_bin= pd.read_csv('clean_collision.csv', parse_dates = [['Date', 'Time']])
data_bin

,Date_Time,Unnamed: 0,Year,Collision Type Descriptor,Road Surface Conditions,Weather Conditions,Number of Vehicles Involved
0,2016-05-15 10:38:00,299452,2016,HEAD ON,Dry,Cloudy,2
1,2016-05-20 00:00:00,299453,2016,Unknown,Dry,Clear,2
2,2016-08-15 19:29:00,299454,2016,OTHER,Dry,Cloudy,1
3,2016-03-30 12:55:00,299457,2016,OVERTAKING,Dry,Clear,2
4,2016-07-09 20:10:00,299459,2016,OTHER,Wet,Rain,1
5,2016-06-01 16:00:00,299464,2016,RIGHT TURN (6),Dry,Clear,2
6,2016-11-13 23:35:00,299467,2016,OTHER,Dry,Clear,1
7,2016-10-20 05:45:00,299472,2016,OTHER,Dry,Clear,1
8,2016-10-30 02:30:00,299473,2016,RIGHT ANGLE,Dry,Clear,2
9,2016-07-01 14:27:00,299476,2016,REAR END,Dry,Clear,2
10,2016-09-19 14:23:00,299479,2016,OTHER,Wet,Rain,1
11,2016-11-14 20:30:00,299482,2016,OTHER,Dry,Clear,1
12,2016-01-20 14:40:00,299483,2016,OTHER,Dry,Cloudy,3
13,2016-05-31 08:00:00,299484,2016,REAR END,Dry,Clear,2
14,2016-07-29 16:22:00,299485,2016,REAR END,Dry,Clear,2
15,2016-04-18 12:58:00,299486,2016,REAR END,Dry,Clear,2
16,2016-02-12 17:08:00,299489,2016,OVERTAKING,Dry,Clear,2
17,2016-10-30 09:00:00,299492,2016,HEAD ON,Other,Clear,2
18,2016-09-23 20:00:00,299495,2016,REAR END,Dry,Clear,2
19,2016-02-17 14:05:00,299496,2016,LEFT TURN (3),Dry,Cloudy,2
20,2016-04-19 12:20:00,299497,2016,SIDESWIPE,Unknown,Unknown,2
21,2016-06-25 18:00:00,299499,2016,LEFT TURN (3),Dry,Clear,2
22,2016-04-02 21:25:00,299500,2016,HEAD ON,Dry,Cloudy,2
23,2016-03-20 12:31:00,299502,2016,LEFT TURN (3),Unknown,Unknown,2
24,2016-07-04 23:58:00,299505,2016,Unknown,Wet,Rain,2
25,2016-08-28 16:15:00,299506,2016,OTHER,Dry,Clear,4
26,2016-11-18 03:40:00,299508,2016,OTHER,Dry,Clear,1
27,2016-05-09 23:41:00,299510,2016,OTHER,Dry,Clear,1
28,2016-11-01 14:45:00,299511,2016,OTHER,Dry,Clear,3
29,2016-06-24 06:40:00,299512,2016,REAR END,Dry,Clear,2
...,...,...,...,...,...,...,...
301878,2016-10-07 15:10:00,895864,2016,OTHER,Dry,Clear,1
301879,2016-12-29 21:38:00,895865,2016,OTHER,Dry,Cloudy,1
301880,2016-05-06 04:20:00,895869,2016,RIGHT ANGLE,Wet,Rain,2
301881,2016-04-14 20:01:00,895871,2016,RIGHT ANGLE,Dry,Clear,2
301882,2016-09-23 10:25:00,895872,2016,OTHER,Dry,Cloudy,3
301883,2016-12-15 21:10:00,895876,2016,RIGHT ANGLE,Snow/Ice,Snow,2
301884,2016-06-01 02:19:00,895879,2016,OTHER,Dry,Clear,1
301885,2016-04-29 10:55:00,895880,2016,OTHER,Wet,Rain,1
301886,2016-11-23 08:20:00,895881,2016,OVERTAKING,Dry,Clear,2
301887,2016-02-03 08:16:00,895883,2016,SIDESWIPE,Snow/Ice,Sleet/Hail/Freezing Rain,2
301888,2016-11-24 07:30:00,895884,2016,OTHER,Dry,Cloudy,1
301889,2016-03-26 18:12:00,895887,2016,REAR END,Dry,Clear,2
301890,2016-12-31 04:30:00,895888,2016,OTHER,Wet,Clear,1
301891,2016-04-04 11:00:00,895889,2016,Unknown,Unknown,Unknown,2
301892,2016-04-17 23:30:00,895891,2016,OTHER,Dry,Clear,3
301893,2016-10-25 14:45:00,895892,2016,LEFT TURN (3),Dry,Clear,2
301894,2016-07-20 15:44:00,895893,2016,RIGHT ANGLE,Dry,Cloudy,2
301895,2016-10-20 12:38:00,895894,2016,REAR END,Wet,Rain,2
301896,2016-11-12 03:23:00,895895,2016,OTHER,Dry,Clear,3
301897,2016-01-05 07:38:00,895896,2016,OTHER,Snow/Ice,Cloudy,1
301898,2016-06-02 16:35:00,895898,2016,RIGHT ANGLE,Dry,Clear,2
301899,2016-06-14 19:25:00,895900,2016,OTHER,Dry,Clear,1
301900,2016-11-28 08:50:00,895901,2016,OVERTAKING,Dry,Clear,2
301901,2016-05-21 21:30:00,895906,2016,LEFT TURN (3),Wet,Rain,2
301902,2016-09-25 11:54:00,895908,2016,OTHER,Dry,Clear,1
301903,2016-05-25 17:18:00,895910,2016,RIGHT ANGLE,Dry,Clear,2
301904,2016-11-27 18:19:00,895911,2016,OTHER,Dry,Cloudy,1
301905,2016-04-27 16:57:00,895912,2016,OTHER,Dry,Clear,1
301906,2016-12-06 21:50:00,895913,2016,RIGHT ANGLE,Snow/Ice,Snow,2
301907,2016-01-07 12:35:00,895915,2016,OTHER,Dry,Cloudy,2

In [41]:
data_bin["Datetime"] = data_bin["Date"] +" "+ data_bin["Time"]

data_bin

KeyError: 'Date'

In [ ]:
data_bin = data_bin[['Year','Collision Type Descriptor', 'Road Surface Conditions', 'Weather Conditions', 'Number of Vehicles Involved', 'Datetime']]
data_bin

In [ ]:
data_bin.sort_values(by='Datetime',ascending=True)

In [ ]:
data_year.to_csv("clean_collision1.csv", mode="w")