In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# City Data

In [2]:
data_city= pd.read_csv('Historical weather data/city_attributes.csv')
data_city.head()
type(data_city)

pandas.core.frame.DataFrame

# Humidity_Data

In [3]:
data2=pd.read_csv('Historical weather data/humidity.csv')
data2=data2.set_index('datetime')
data2

,Vancouver,Portland,San Francisco,Seattle,Los Angeles,San Diego,Las Vegas,Phoenix,Albuquerque,Denver,...,Philadelphia,New York,Montreal,Boston,Beersheba,Tel Aviv District,Eilat,Haifa,Nahariyya,Jerusalem
datetime,,,,,,,,,,,,,,,,,,,,,
2012-10-01 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN
2012-10-01 13:00:00,76.0,81.0,88.0,81.0,88.0,82.0,22.0,23.0,50.0,62.0,...,71.0,58.0,93.0,68.0,50.0,63.0,22.0,51.0,51.0,50.0
2012-10-01 14:00:00,76.0,80.0,87.0,80.0,88.0,81.0,21.0,23.0,49.0,62.0,...,70.0,57.0,91.0,68.0,51.0,62.0,22.0,51.0,51.0,50.0
2012-10-01 15:00:00,76.0,80.0,86.0,80.0,88.0,81.0,21.0,23.0,49.0,62.0,...,70.0,57.0,87.0,68.0,51.0,62.0,22.0,51.0,51.0,50.0
2012-10-01 16:00:00,77.0,80.0,85.0,79.0,88.0,81.0,21.0,23.0,49.0,62.0,...,69.0,57.0,84.0,68.0,52.0,62.0,22.0,51.0,51.0,50.0
2012-10-01 17:00:00,78.0,79.0,84.0,79.0,88.0,80.0,21.0,24.0,49.0,63.0,...,69.0,57.0,80.0,68.0,54.0,62.0,23.0,51.0,51.0,50.0
2012-10-01 18:00:00,78.0,79.0,83.0,78.0,88.0,80.0,21.0,24.0,49.0,63.0,...,68.0,56.0,76.0,68.0,55.0,63.0,23.0,51.0,51.0,50.0
2012-10-01 19:00:00,79.0,78.0,82.0,77.0,88.0,80.0,21.0,24.0,49.0,63.0,...,68.0,56.0,72.0,68.0,56.0,63.0,23.0,51.0,51.0,50.0
2012-10-01 20:00:00,79.0,78.0,81.0,77.0,88.0,79.0,20.0,25.0,49.0,64.0,...,67.0,56.0,68.0,68.0,57.0,63.0,24.0,51.0,51.0,50.0
2012-10-01 21:00:00,80.0,77.0,80.0,76.0,88.0,79.0,20.0,25.0,49.0,64.0,...,67.0,55.0,64.0,68.0,58.0,64.0,24.0,51.0,51.0,50.0
2012-10-01 22:00:00,81.0,77.0,79.0,76.0,88.0,78.0,20.0,26.0,48.0,65.0,...,66.0,55.0,61.0,68.0,59.0,64.0,24.0,51.0,51.0,50.0
2012-10-01 23:00:00,81.0,77.0,78.0,75.0,88.0,78.0,20.0,26.0,48.0,65.0,...,66.0,55.0,57.0,68.0,60.0,64.0,25.0,51.0,51.0,50.0
2012-10-02 00:00:00,82.0,76.0,77.0,75.0,88.0,78.0,20.0,26.0,48.0,65.0,...,65.0,55.0,53.0,68.0,61.0,65.0,25.0,51.0,51.0,50.0
2012-10-02 01:00:00,83.0,76.0,76.0,74.0,88.0,77.0,20.0,27.0,48.0,66.0,...,65.0,54.0,49.0,68.0,62.0,65.0,25.0,51.0,51.0,50.0
2012-10-02 02:00:00,83.0,75.0,75.0,73.0,88.0,77.0,19.0,27.0,48.0,66.0,...,64.0,54.0,45.0,68.0,63.0,65.0,26.0,51.0,51.0,50.0
2012-10-02 03:00:00,84.0,75.0,74.0,73.0,88.0,77.0,19.0,27.0,48.0,66.0,...,64.0,54.0,42.0,68.0,64.0,66.0,26.0,51.0,51.0,50.0
2012-10-02 04:00:00,84.0,75.0,73.0,72.0,88.0,76.0,19.0,28.0,48.0,67.0,...,63.0,53.0,38.0,68.0,66.0,66.0,26.0,51.0,51.0,50.0
2012-10-02 05:00:00,85.0,74.0,72.0,72.0,88.0,76.0,19.0,28.0,48.0,67.0,...,63.0,53.0,34.0,68.0,67.0,66.0,26.0,51.0,51.0,50.0
2012-10-02 06:00:00,86.0,74.0,71.0,71.0,88.0,75.0,19.0,29.0,47.0,68.0,...,62.0,53.0,30.0,68.0,68.0,67.0,27.0,51.0,51.0,50.0
2012-10-02 07:00:00,86.0,73.0,70.0,71.0,88.0,75.0,19.0,29.0,47.0,68.0,...,62.0,53.0,26.0,68.0,69.0,67.0,27.0,51.0,51.0,50.0
2012-10-02 08:00:00,87.0,73.0,69.0,70.0,88.0,75.0,18.0,29.0,47.0,68.0,...,61.0,52.0,22.0,68.0,70.0,67.0,27.0,51.0,51.0,50.0
2012-10-02 09:00:00,87.0,73.0,68.0,69.0,88.0,74.0,18.0,30.0,47.0,69.0,...,61.0,52.0,19.0,68.0,71.0,68.0,28.0,51.0,51.0,50.0
2012-10-02 10:00:00,88.0,72.0,67.0,69.0,88.0,74.0,18.0,30.0,47.0,69.0,...,60.0,52.0,15.0,68.0,72.0,68.0,28.0,51.0,51.0,50.0
2012-10-02 11:00:00,89.0,72.0,66.0,68.0,88.0,74.0,18.0,30.0,47.0,69.0,...,60.0,51.0,11.0,68.0,73.0,68.0,28.0,51.0,51.0,50.0
2012-10-02 12:00:00,89.0,71.0,65.0,68.0,88.0,73.0,18.0,31.0,47.0,70.0,...,59.0,51.0,7.0,68.0,74.0,69.0,29.0,51.0,51.0,50.0
2012-10-02 13:00:00,90.0,71.0,64.0,67.0,88.0,73.0,18.0,31.0,47.0,70.0,...,59.0,51.0,NaN,68.0,75.0,69.0,29.0,51.0,51.0,50.0
2012-10-02 14:00:00,91.0,71.0,63.0,67.0,88.0,73.0,18.0,32.0,47.0,71.0,...,59.0,51.0,NaN,68.0,76.0,69.0,29.0,51.0,51.0,50.0
2012-10-02 15:00:00,89.0,76.0,51.0,87.0,88.0,73.0,16.0,17.0,41.0,66.0,...,48.0,52.0,82.0,64.0,78.0,70.0,30.0,51.0,51.0,50.0
2012-10-02 16:00:00,76.0,62.0,56.0,76.0,23.0,22.0,23.0,28.0,40.0,NaN,...,52.0,NaN,NaN,64.0,80.0,66.0,28.0,51.0,51.0,50.0
2012-10-02 17:00:00,76.0,75.0,94.0,58.0,19.0,15.0,18.0,NaN,NaN,NaN,...,43.0,NaN,NaN,64.0,83.0,74.0,36.0,51.0,51.0,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-11-28 19:00:00,NaN,100.0,NaN,100.0,37.0,63.0,26.0,32.0,40.0,42.0,...,36.0,NaN,59.0,32.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-28 20:00:00,NaN,100.0,NaN,100.0,28.0,59.0,21.0,56.0,35.0,39.0,...,36.0,NaN,59.0,32.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-28 21:00:00,NaN,100.0,NaN,93.0,40.0,59.0,18.0,22.0,35.0,36.0,...,38.0,NaN,59.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-28 22:00:00,NaN,100.0,NaN,100.0,23.0,59.0,21.0,53.0,35.0,36.0,...,46.0,NaN,59.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-28 23:00:00,NaN,100.0,NaN,93.0,35.0,61.0,33.0,53.0,28.0,36.0,...,50.0,NaN,74.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 00:00:00,NaN,87.0,NaN,93.0,28.0,77.0,18.0,18.0,34.0,48.0,...,62.0,NaN,64.0,74.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 01:00:00,NaN,93.0,NaN,93.0,37.0,72.0,21.0,21.0,45.0,51.0,...,66.0,NaN,64.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 02:00:00,NaN,93.0,NaN,93.0,42.0,72.0,24.0,50.0,49.0,64.0,...,71.0,NaN,64.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 03:00:00,NaN,87.0,NaN,93.0,52.0,72.0,30.0,29.0,52.0,77.0,...,76.0,NaN,65.0,81.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 04:00:00,NaN,93.0,NaN,81.0,45.0,82.0,37.0,82.0,48.0,68.0,...,76.0,NaN,65.0,87.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 05:00:00,NaN,93.0,NaN,87.0,50.0,71.0,29.0,82.0,45.0,79.0,...,87.0,NaN,65.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 06:00:00,NaN,87.0,NaN,87.0,67.0,67.0,34.0,71.0,52.0,86.0,...,87.0,NaN,69.0,93.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 07:00:00,NaN,87.0,NaN,100.0,82.0,71.0,27.0,66.0,52.0,86.0,...,93.0,NaN,80.0,81.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 08:00:00,NaN,87.0,NaN,87.0,82.0,71.0,25.0,40.0,56.0,85.0,...,87.0,NaN,80.0,81.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 09:00:00,NaN,87.0,NaN,93.0,82.0,76.0,27.0,41.0,60.0,92.0,...,93.0,NaN,93.0,76.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 10:00:00,NaN,87.0,NaN,87.0,87.0,76.0,31.0,40.0,60.0,92.0,...,93.0,NaN,87.0,76.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 11:00:00,NaN,87.0,NaN,100.0,87.0,76.0,25.0,40.0,64.0,92.0,...,93.0,NaN,87.0,87.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 12:00:00,NaN,87.0,NaN,87.0,93.0,76.0,27.0,37.0,69.0,92.0,...,87.0,NaN,86.0,76.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 13:00:00,NaN,87.0,NaN,100.0,93.0,87.0,27.0,71.0,74.0,92.0,...,87.0,NaN,93.0,81.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 14:00:00,NaN,87.0,NaN,100.0,93.0,81.0,31.0,71.0,74.0,64.0,...,81.0,NaN,100.0,66.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 15:00:00,NaN,87.0,NaN,87.0,87.0,93.0,29.0,71.0,74.0,74.0,...,58.0,NaN,93.0,58.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 16:00:00,NaN,87.0,NaN,100.0,82.0,87.0,27.0,76.0,64.0,92.0,...,47.0,NaN,86.0,54.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 17:00:00,NaN,87.0,NaN,100.0,58.0,77.0,25.0,100.0,52.0,74.0,...,33.0,NaN,75.0,44.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 18:00:00,NaN,87.0,NaN,100.0,42.0,72.0,28.0,88.0,49.0,52.0,...,50.0,NaN,73.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 19:00:00,NaN,81.0,NaN,81.0,32.0,72.0,20.0,72.0,42.0,39.0,...,29.0,NaN,73.0,41.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 20:00:00,NaN,81.0,NaN,93.0,24.0,72.0,18.0,68.0,37.0,18.0,...,27.0,NaN,64.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 21:00:00,NaN,71.0,NaN,87.0,21.0,72.0,18.0,73.0,34.0,12.0,...,29.0,NaN,59.0,74.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 22:00:00,NaN,71.0,NaN,93.0,23.0,68.0,17.0,60.0,32.0,15.0,...,31.0,NaN,66.0,74.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 23:00:00,NaN,71.0,NaN,87.0,14.0,63.0,17.0,33.0,30.0,28.0,...,26.0,NaN,58.0,56.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-30 00:00:00,NaN,76.0,NaN,75.0,56.0,72.0,17.0,23.0,34.0,31.0,...,32.0,NaN,58.0,56.0,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
pivot=pd.DataFrame(data2.unstack(level=0))
data2_clean=pivot.reset_index().rename(columns={'level_0':'City', 0:'Humidity %'})
data2_clean.head()

        City             datetime  Humidity %
0  Vancouver  2012-10-01 12:00:00         NaN
1  Vancouver  2012-10-01 13:00:00        76.0
2  Vancouver  2012-10-01 14:00:00        76.0
3  Vancouver  2012-10-01 15:00:00        76.0
4  Vancouver  2012-10-01 16:00:00        77.0

In [5]:
data_humidity=data2_clean.dropna(axis=0,how='any')
data_humidity.head()

        City             datetime  Humidity %
1  Vancouver  2012-10-01 13:00:00        76.0
2  Vancouver  2012-10-01 14:00:00        76.0
3  Vancouver  2012-10-01 15:00:00        76.0
4  Vancouver  2012-10-01 16:00:00        77.0
5  Vancouver  2012-10-01 17:00:00        78.0

# Pressure Data

In [6]:
data3=pd.read_csv('Historical weather data/pressure.csv')
data3=data3.set_index('datetime')
data3

,Vancouver,Portland,San Francisco,Seattle,Los Angeles,San Diego,Las Vegas,Phoenix,Albuquerque,Denver,...,Philadelphia,New York,Montreal,Boston,Beersheba,Tel Aviv District,Eilat,Haifa,Nahariyya,Jerusalem
datetime,,,,,,,,,,,,,,,,,,,,,
2012-10-01 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1011.0,NaN,NaN,NaN
2012-10-01 13:00:00,NaN,1024.0,1009.0,1027.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,1001.0,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-01 14:00:00,NaN,1024.0,1009.0,1027.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,986.0,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-01 15:00:00,NaN,1024.0,1009.0,1028.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,945.0,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-01 16:00:00,NaN,1024.0,1009.0,1028.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,904.0,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-01 17:00:00,NaN,1024.0,1009.0,1029.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,863.0,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-01 18:00:00,NaN,1024.0,1010.0,1030.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,822.0,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-01 19:00:00,NaN,1024.0,1010.0,1031.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-01 20:00:00,NaN,1024.0,1010.0,1031.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-01 21:00:00,NaN,1024.0,1010.0,1032.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-01 22:00:00,NaN,1024.0,1011.0,1033.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-01 23:00:00,NaN,1024.0,1011.0,1034.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 00:00:00,NaN,1024.0,1011.0,1035.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 01:00:00,NaN,1024.0,1011.0,1035.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 02:00:00,NaN,1024.0,1012.0,1036.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 03:00:00,NaN,1024.0,1012.0,1037.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 04:00:00,NaN,1024.0,1012.0,1038.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 05:00:00,NaN,1024.0,1012.0,1038.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 06:00:00,NaN,1024.0,1013.0,1039.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 07:00:00,NaN,1024.0,1013.0,1040.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 08:00:00,NaN,1024.0,1013.0,1041.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 09:00:00,807.0,1024.0,1013.0,1042.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 10:00:00,849.0,1024.0,1014.0,1042.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 11:00:00,890.0,1024.0,1014.0,1043.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 12:00:00,932.0,1024.0,1014.0,1044.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 13:00:00,973.0,1024.0,1014.0,1045.0,1013.0,1013.0,1018.0,1013.0,1024.0,1028.0,...,1014.0,1012.0,NaN,1014.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 14:00:00,1015.0,1024.0,1015.0,1046.0,1013.0,1013.0,1019.0,1014.0,1025.0,1028.0,...,1014.0,1012.0,NaN,1015.0,984.0,1012.0,1010.0,1013.0,1013.0,990.0
2012-10-02 15:00:00,1027.0,1024.0,1016.0,1026.0,1013.0,1014.0,1019.0,1014.0,1026.0,1028.0,...,1014.0,1012.0,1002.0,1014.0,985.0,1013.0,1011.0,1013.0,1013.0,990.0
2012-10-02 16:00:00,1015.0,1024.0,1011.0,1026.0,1014.0,1014.0,1019.0,1014.0,1016.0,1027.0,...,1014.0,NaN,NaN,1014.0,985.0,1013.0,1012.0,1013.0,1013.0,990.0
2012-10-02 17:00:00,1014.0,1027.0,1001.0,1027.0,1014.0,1014.0,1020.0,NaN,NaN,1026.0,...,1013.0,NaN,NaN,1014.0,986.0,1014.0,1012.0,1013.0,1013.0,990.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-11-28 19:00:00,NaN,1017.0,NaN,1014.0,1016.0,1017.0,1021.0,1017.0,1022.0,1027.0,...,1027.0,NaN,1018.0,1028.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-28 20:00:00,NaN,1016.0,NaN,1014.0,1016.0,1017.0,1020.0,1017.0,1022.0,1026.0,...,1027.0,NaN,1016.0,1027.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-28 21:00:00,NaN,1016.0,NaN,1014.0,1015.0,1016.0,1019.0,1016.0,1022.0,1026.0,...,1026.0,NaN,1015.0,1027.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-28 22:00:00,NaN,1017.0,NaN,1014.0,1014.0,1016.0,1018.0,1016.0,1022.0,1026.0,...,1026.0,NaN,1015.0,1028.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-28 23:00:00,NaN,1017.0,NaN,1014.0,961.0,980.0,920.0,1016.0,1023.0,1026.0,...,1026.0,NaN,1019.0,1028.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 00:00:00,NaN,1020.0,NaN,1016.0,1013.0,1015.0,1018.0,1015.0,1024.0,1027.0,...,1026.0,NaN,1014.0,1026.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 01:00:00,NaN,1021.0,NaN,1016.0,1014.0,1015.0,1018.0,1015.0,1025.0,1027.0,...,1026.0,NaN,1012.0,1026.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 02:00:00,NaN,1022.0,NaN,1017.0,1014.0,1015.0,1018.0,1015.0,1026.0,1027.0,...,1025.0,NaN,1011.0,1025.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 03:00:00,NaN,1022.0,NaN,1018.0,1014.0,1016.0,1019.0,1015.0,1027.0,1026.0,...,1025.0,NaN,1010.0,1024.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 04:00:00,NaN,1023.0,NaN,1019.0,1015.0,1016.0,1019.0,1016.0,1027.0,1026.0,...,1025.0,NaN,1011.0,1023.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 05:00:00,NaN,1025.0,NaN,1021.0,1017.0,1015.0,1019.0,1016.0,1027.0,1025.0,...,1023.0,NaN,1009.0,1020.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 06:00:00,NaN,1026.0,NaN,1021.0,1015.0,1016.0,1019.0,1017.0,1028.0,1024.0,...,1022.0,NaN,1009.0,1021.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 07:00:00,NaN,1026.0,NaN,1023.0,1016.0,1016.0,1019.0,1017.0,1027.0,1023.0,...,1022.0,NaN,1009.0,1020.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 08:00:00,NaN,1027.0,NaN,1025.0,1016.0,1016.0,1019.0,1017.0,1027.0,1022.0,...,1021.0,NaN,1010.0,1016.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 09:00:00,NaN,1028.0,NaN,1025.0,1016.0,1016.0,1019.0,1017.0,1027.0,1021.0,...,1021.0,NaN,1011.0,1016.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 10:00:00,NaN,1028.0,NaN,1026.0,1016.0,1016.0,1019.0,1017.0,1027.0,1021.0,...,1020.0,NaN,1010.0,1015.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 11:00:00,NaN,1029.0,NaN,1026.0,1015.0,1016.0,1019.0,1017.0,1027.0,1020.0,...,1020.0,NaN,1011.0,1016.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 12:00:00,NaN,1029.0,NaN,1027.0,1015.0,1015.0,1019.0,1017.0,1027.0,1019.0,...,1020.0,NaN,1011.0,1015.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 13:00:00,NaN,1030.0,NaN,1027.0,1016.0,1015.0,1020.0,1017.0,1027.0,1019.0,...,1021.0,NaN,1012.0,1016.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 14:00:00,NaN,1030.0,NaN,1028.0,1016.0,1015.0,1020.0,1017.0,1027.0,1016.0,...,1021.0,NaN,1013.0,1015.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 15:00:00,NaN,1031.0,NaN,1029.0,1016.0,1016.0,1021.0,1018.0,1028.0,1016.0,...,1021.0,NaN,1013.0,1015.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 16:00:00,NaN,1031.0,NaN,1029.0,1016.0,1017.0,1021.0,1018.0,1028.0,1018.0,...,1021.0,NaN,1014.0,1014.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 17:00:00,NaN,1031.0,NaN,1029.0,1016.0,1017.0,1022.0,1019.0,1028.0,1019.0,...,1020.0,NaN,1016.0,1014.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 18:00:00,NaN,1032.0,NaN,1029.0,1017.0,1018.0,1022.0,1019.0,1028.0,1019.0,...,1020.0,NaN,1017.0,1014.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 19:00:00,NaN,1032.0,NaN,1030.0,1017.0,1017.0,1022.0,1019.0,1026.0,1018.0,...,1020.0,NaN,1019.0,1015.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 20:00:00,NaN,1031.0,NaN,1030.0,1016.0,1017.0,1021.0,1018.0,1025.0,1016.0,...,1021.0,NaN,1021.0,1017.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 21:00:00,NaN,1030.0,NaN,1030.0,1016.0,1017.0,1020.0,1018.0,1024.0,1018.0,...,1021.0,NaN,1023.0,1019.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 22:00:00,NaN,1030.0,NaN,1029.0,1015.0,1016.0,1020.0,1017.0,1024.0,1018.0,...,1022.0,NaN,1024.0,1019.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-29 23:00:00,NaN,1029.0,NaN,1028.0,1016.0,1016.0,1020.0,1016.0,1024.0,1020.0,...,1023.0,NaN,1026.0,1022.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-30 00:00:00,NaN,1029.0,NaN,1028.0,1015.0,1017.0,1019.0,1016.0,1024.0,1021.0,...,1024.0,NaN,1027.0,1023.0,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
pivot2=pd.DataFrame(data3.unstack(level=0))
data3_clean=pivot.reset_index().rename(columns={'level_0':'City', 0:'Pressure'})
data_pressure=data3_clean.dropna(axis=0,how='any')

data_pressure.head()

        City             datetime  Pressure
1  Vancouver  2012-10-01 13:00:00      76.0
2  Vancouver  2012-10-01 14:00:00      76.0
3  Vancouver  2012-10-01 15:00:00      76.0
4  Vancouver  2012-10-01 16:00:00      77.0
5  Vancouver  2012-10-01 17:00:00      78.0

# temperature

In [8]:
data4=pd.read_csv('Historical weather data/temperature.csv')
data4=data4.set_index('datetime')

pivot3=pd.DataFrame(data4.unstack(level=0))
data4_clean=pivot3.reset_index().rename(columns={'level_0':'City', 0:'Temperature in Kelvin'})

data_temp=data4_clean.dropna(axis=0,how='any')

data_temp.head()

        City             datetime  Temperature in Kelvin
1  Vancouver  2012-10-01 13:00:00             284.630000
2  Vancouver  2012-10-01 14:00:00             284.629041
3  Vancouver  2012-10-01 15:00:00             284.626998
4  Vancouver  2012-10-01 16:00:00             284.624955
5  Vancouver  2012-10-01 17:00:00             284.622911

# weather description

In [9]:
data5=pd.read_csv('Historical weather data/weather_description.csv')
data5=data5.set_index('datetime')


pivot4=pd.DataFrame(data5.unstack(level=0))
data5_clean=pivot4.reset_index().rename(columns={'level_0':'City', 0:'weather'})

data_weather=data5_clean.dropna(axis=0,how='any')

data_weather.head()

        City             datetime        weather
1  Vancouver  2012-10-01 13:00:00           mist
2  Vancouver  2012-10-01 14:00:00  broken clouds
3  Vancouver  2012-10-01 15:00:00  broken clouds
4  Vancouver  2012-10-01 16:00:00  broken clouds
5  Vancouver  2012-10-01 17:00:00  broken clouds

# wind speed

In [10]:
data6=pd.read_csv('Historical weather data/wind_speed.csv')
data6=data6.set_index('datetime')


pivot5=pd.DataFrame(data6.unstack(level=0))
data6_clean=pivot5.reset_index().rename(columns={'level_0':'City', 0:'wind speed'})

data_wind_speed=data6_clean.dropna(axis=0,how='any')

data_wind_speed.head()

        City             datetime  wind speed
1  Vancouver  2012-10-01 13:00:00         0.0
2  Vancouver  2012-10-01 14:00:00         0.0
3  Vancouver  2012-10-01 15:00:00         0.0
4  Vancouver  2012-10-01 16:00:00         0.0
5  Vancouver  2012-10-01 17:00:00         0.0

# combined data

In [11]:
parameter_data=[data_temp, data_pressure,data_humidity, data_weather, data_wind_speed]

combine=data_city
print(combine.head())
for i in range(len(parameter_data)):
    combined= pd.merge_ordered(combine, parameter_data[i], on='City', how='outer')
    print(combined.head())
    combine=combined
    
    
combined

            City        Country   Latitude   Longitude
0      Vancouver         Canada  49.249660 -123.119339
1       Portland  United States  45.523449 -122.676208
2  San Francisco  United States  37.774929 -122.419418
3        Seattle  United States  47.606209 -122.332069
4    Los Angeles  United States  34.052231 -118.243683
          City        Country   Latitude   Longitude             datetime  \
0  Albuquerque  United States  35.084492 -106.651138  2012-10-01 13:00:00
1  Albuquerque  United States  35.084492 -106.651138  2012-10-01 14:00:00
2  Albuquerque  United States  35.084492 -106.651138  2012-10-01 15:00:00
3  Albuquerque  United States  35.084492 -106.651138  2012-10-01 16:00:00
4  Albuquerque  United States  35.084492 -106.651138  2012-10-01 17:00:00

   Temperature in Kelvin
0             285.120000
1             285.154558
2             285.233952
3             285.313345
4             285.392738

MemoryError:

In [ ]:
combined_1=data_city.merge(data_temp, on='City', how='outer')
combined_1.head()

In [ ]:
combined_2=combined_1.merge(data_pressure, on='City', how='outer')
combined_2